version: '3'
services:
  lb:
    image: haproxy:2.9-alpine
    ports:
      - 9999:9999
      - 9994:9994
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app01
      - app02
    deploy:
      resources:
        limits:
          memory: 120MB
          cpus: "0.3"
  app01:
    build: web/
    ports:
      - 8081:8080
    environment:
      PORT: 8080
      DB_HOST: db
      PG__POOL__MAX_SIZE: 175
      PG__POOL__TIMEOUTS__WAIT__SECS: 2
    deploy:
      resources:
        limits:
          memory: 10MB
          cpus: "0.2"
  app02:
    build: web/
    ports:
      - 8082:8080
    environment:
      PORT: 8080
      DB_HOST: db
      PG__POOL__MAX_SIZE: 175
      PG__POOL__TIMEOUTS__WAIT__SECS: 2
    deploy:
      resources:
        limits:
          memory: 10MB
          cpus: "0.2"

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init_postgres_scripts:/docker-entrypoint-initdb.d/
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinha
    healthcheck: 
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 300MB
          cpus: '0.8'


