version: "3.5"

services:
  api01: &api
    image: lucasmula125/rinha-backend-2024
    hostname: api01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gercino2
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=db
      - PORT=5432
      - POSTGRES_POOLSIZE=10
      - ROCKET_LIMITS={json="1024kib"}
    ports:
      - "3001:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50mb"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:8000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20mb"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=Gercino2
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "430mb"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
