services:
  db:
    image: postgres:16-bookworm
    command:
      [
        "-c",
        "fsync=off",
        "-c",
        "full_page_writes=false",
        "-c",
        "synchronous_commit=off",
      ]
    environment:
      POSTGRES_DB: "rinha_backend"
      POSTGRES_USER: "rinha"
      POSTGRES_PASSWORD: "backend"
    healthcheck:
      test: PGPASSWORD=backend psql -h db -U rinha rinha_backend -c  "SELECT count(*) FROM Cliente;"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "300mb"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    image: droderuan/node-rinha-backend-2024
    command: npm run start:prod
    environment:
      DB_HOST: "db"
      DB_POOL: 15
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: "100mb"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
