services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.18"
          memory: "30MB"

  api01: &api
    image: gmorum/rinha-2024q1:ktor-mongo-v1-native
    ports:
      - "8070:8080"
    environment:
      - INIT_DB=true
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.52"
          memory: "120MB"

  api02:
    <<: *api
    depends_on:
      - mongo
    environment:
      - INIT_DB=false
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - "8060:8080"

  mongo:
    image: mongo:7.0.3
    ports:
      - "27017:27017"
    command: --quiet --logpath /dev/null
    deploy:
      resources:
        limits:
          cpus: "0.28"
          memory: "280MB"
